name: ci-django
on:
  push:
    branches: [main]
    paths: ['packages/django/**']
  pull_request:
    branches: [main]
    paths: ['packages/django/**']
jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: packages/django
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
      - name: install poetry
        run: pip install poetry
      - name: install dependencies
        run: poetry install
      - name: run tests
        run: poetry run python runtests.py
